materialize:
  outputs:
    staging:
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: db_staging
      schema: public
      cluster: "{{ env_var('CI_TAG') }}"
    production:
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: db_production
      schema: public
      cluster: demo
  target: staging
