materialize:
  outputs:
    staging:
      type: materialize
      host: "{{ env_var('MZ_HOST_STG') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD_STG') }}"
      database: db_staging
      cluster: "{{ env_var('CI_TAG') }}"
      schema: qck
    production:
      type: materialize
      host: "{{ env_var('MZ_HOST_PROD') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD_PROD') }}"
      database: materialize
      cluster: quickstart
      schema: qck
  target: staging