materialize:
  outputs:
    staging:
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: db_staging
      cluster: "{{ env_var('CI_TAG') }}"
      schema: qck
    production:
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: db_production
      cluster: quickstart
      schema: qck
  target: staging
