name: dbt ci

# Run the workflow when a commit is pushed to any branch except main
on:
  pull_request:
  push:
    branches:
      - '!main'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and setup python
      #----------------------------------------------
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      # Install dbt packages defined in packages.yml
      - name: dbt deps
        run: |
          source .venv/bin/activate
          dbt deps

      # Retrieve the PR number and set it to the variable findPR
      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.3.2
        id: findPR
        with:
          state: open
          sha: ${{ github.event.pull_request.head.sha }}
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      #----------------------------------------------
      # dbt
      #----------------------------------------------
      # 
      - name: dbt build
        env:
          MZ_HOST_STG: ${{ secrets.MZ_HOST_STG }}
          MZ_USER: ${{ secrets.MZ_USER }}
          MZ_PASSWORD_STG: ${{ secrets.MZ_PASSWORD_STG }}
          CI_TAG: "${{ format('{0}_{1}', 'gh_ci', steps.findPr.outputs.pr) }}"
        run: |
          source .venv/bin/activate
          dbt run-operation create_cluster --args '{cluster_name: $CI_TAG}'
          dbt build --profiles-dir ./
